### ISSUE TITLE
Error Deploying `bundle-examples/knowledge_base/development_cluster` Bundle.

### ISSUE THREAD

**Issue by chander-pal** [databricks/bundle-examples#40]
I've cloned the repository and am attempting to deploy the bundle-examples/knowledge_base/development_cluster bundle. However, I'm encountering the following error:
<img width="203" alt="image" src="https://github.com/user-attachments/assets/dc8eefa7-972e-49d0-95f8-a6bc7361f951">
`databricks.yml` section
```

targets:
  dev:
    mode: development
    default: true
    cluster_id: ${resources.clusters.development_cluster.id}

    resources:
      clusters:
        development_cluster:
          cluster_name: Development cluster
```

Error
``` 
Warning: unknown field: cluster_id
  at targets.dev
  in databricks.yml:23:5

Warning: unknown field: clusters
  at targets.dev.resources
  in databricks.yml:26:7 
```
In my case, I'm trying to override the cluster configuration for the development environment. Specifically, I want to use a common cluster for development while using a job-specific cluster for production workloads for another project.

Could there have been recent updates to Bundles that aren't reflected in this example?
